apiVersion: v1
kind: Service
metadata:
  namespace: kic
  name: kic-media-service
spec:
  ports:
    - port: 50051
  selector:
    app: kic-media
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kic
  name: kic-media
spec:
  selector:
    matchLabels:
      app: kic-media
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: kic
      labels:
        app: kic-media
    spec:
      containers:
        - image: gcr.io/keeping-it-casual/kic-media:dev #gcr.io/PROJECT_ID/IMAGE:TAG
          name: kic-media
          ports:
            - containerPort: 50051
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri
                  key: mongo-uri
            - name: PRODUCTION
              value: "true"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: PORT
              value: "50051"
      volumes:
        - name: google-cloud-key
          secret:
            secretName: gcloud-key